DEFAULT_CONFIG_PATH = "config/traffic_monitor_config.json"
CAMERA_STREAM_URL_ENV = "CAMERA_STREAM_URL"
REGIONS_CONFIG_KEY = "regions"
CV2_WINDOW_NAME = "Traffic Monitor"
NUM_PREDICT_ITERATIONS = 10
NUM_TRAINING_FRAMES = 100
FPS = 10
MAX_NUM_FRAMES_LIVE_PREDICTION = 250
